### ISSUE TITLE
Update instruction banner in Rockwell with clicks

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#205]
In the banner at the top of the feed, we are currently instructing participants to
> retweet and like as you normally would

We need to update this so that it reads

> retweet, **like, and click** as you normally would

**Comment by glciampaglia** [comment]
@obbergeron please let us know if this is OK to add to the banner at the top of the feed in Rockwell. Should we also add language saying that there may be a delay / some retweets/likes may not appear at all?

**Comment by obbergeron** [comment]
add this to rockwell directly, or on qualtrics as well? 

re: language on delay, Brendan suggested on Slack: "(Note: Due to technical limitations, your retweets and likes may propagate to your Twitter feed with some delay. If an error occurs, it is also possible that some may not appear in your feed.)"

**Comment by glciampaglia** [comment]
@obbergeron looks good. I suggest we add this only on qualtrics, as the banner on Rockwell is already pretty long.

**Comment by saumyabhadani95** [comment]
The banner on the top of the feed already includes instruction to click on links. I don't remember changing it but I think we did it immediately after pilot 3 wave 2. Anyways, it looks like the following:

![Image](https://github.com/CSDL-UMD/Rockwell/assets/14941766/03326ecb-f80b-4b4e-bb03-43cc9ad1470e)
