### ISSUE TITLE
Load a second screen with out-of-network inventory

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#214]
At the meeting on Sept 8 meeting we discussed the problem of filling in-network inventory with additional news tweets, and Fil proposed to to have participants to go through two different feeds, one constructed just from in-network inventory, and another one just with out-of-network one. 

We discussed what is the simplest way to implement this, and we think that this could be achieved with a small change in the database. Currently, we store the score of each user--tweet pair in a table. We can add an additional column that indicates what inventory/screen the score refers to. When we compute scores, the script that update the database needs to be able to set this new variable accordingly.

In the frontend, when the user has clicked the "Next" button to advance, Rockwell should load the second screen instead of the debriefing page. The user then interacts with the second feed. When they click "Next" again, it will now take the user the debriefing page, with the instructions to return to Qualtrics.

To discuss with @obbergeron and Brendan: do we randomize across feeds? One concern is that engagement may be low in the out-of-network just because it comes after the in-network one.

**Comment by obbergeron** [comment]
Do you mean randomize the order of the two screens? I guess there are two decisions that we can independently make, which forms a sort a 2x2 table: 

| | Randomize feed order  | Fixed feed order |
|  ------------- | ------------- | ------------- |
| **Fixed feed ranking <br>algo across feeds** |   |   |
|**Independently randomize<br> algo** |   |   |

I would lean toward the upper-left cell. I lean quite strongly in favor of randomizing the order of the in-network vs out-of-network feeds. Hopefully, we do this and find a null order effect and can pool everything. what's less clear to me is what we do if there is some order effect. but regardless of what we do, it's probably something we'd want to know anyways. 

regarding the other decision, I think fixed algo within-respondent makes most sense. otherwise, we get into even more complexity that we need to test for. 

but i'm not wedded to any of this, so any thoughts are welcome.

**Comment by brendannyhan** [comment]
adapted from what I wrote on Slack:

hey all, I think olivier wrote back already on GH, but what we talked about is randomizing order at the participant level creates potential order effects so my instinct is personalized feed first so it's clean (no spillover from other screen being first). even if there's lower engagement, we have more tweets they can engage with so we'll get good data, whereas if personalized is second, lower engagement + fewer relevant item = <death>

on randomizing treatment, my instinct is to do it at the respondent-level - i.e., hold treatment assignment fixed between screens

**Comment by glciampaglia** [comment]
OK, so we will go with upper right cell in Oliver's column:
- Type of algorithm (i.e. CF vs CF+D) is assigned at respondent-level
- Type of inventory (in-network aka "personalized" vs out-of-network) follows fixed order for all participants (in-network first, followed by out-of-network).
